// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using HotelReservationSystem.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace HotelReservationSystem.Models
{
    public partial class HotelReservationSystemContext
    {
        private IHotelReservationSystemContextProcedures _procedures;

        public virtual IHotelReservationSystemContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new HotelReservationSystemContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IHotelReservationSystemContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class HotelReservationSystemContextProcedures : IHotelReservationSystemContextProcedures
    {
        private readonly HotelReservationSystemContext _context;

        public HotelReservationSystemContextProcedures(HotelReservationSystemContext context)
        {
            _context = context;
        }

        public virtual async Task<List<sp_GetMonthlyReservationReportResult>> sp_GetMonthlyReservationReportAsync(string YearMonth, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "YearMonth",
                    Size = 14,
                    Value = YearMonth ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<sp_GetMonthlyReservationReportResult>("EXEC @returnValue = [dbo].[sp_GetMonthlyReservationReport] @YearMonth = @YearMonth", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
