// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using HotelReservationSystem.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace HotelReservationSystem.Models
{
    public partial interface IHotelReservationSystemContextProcedures
    {
        Task<List<sp_GetMonthlyReservationReportResult>> sp_GetMonthlyReservationReportAsync(string YearMonth, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
