// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace HotelReservationSystem.Models
{
    public partial class sp_GetMonthlyReservationReportResult
    {
        public string YearMonth { get; set; }
        public int? TotalReservations { get; set; }
        public int? ConfirmedReservations { get; set; }
        public int? CancelledReservations { get; set; }
    }
}
